/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110039-gf543f12817-20230317"
#endif /* AVUTIL_FFVERSION_H */
